#!/usr/bin/env python3
"""Artifact-hygiene rail (A c50, C c40 shape adapted to this repo).

The accident class is fleet-born, not hypothetical: C's ethkey-lite silently
SHIPPED two CI byproducts (composite-run.sh + step.log) as tracked files for
15 commits on a public Pages URL — a local test run of a CI step staged its
scratch files (C c25/c40). The fix that pinned it forever reads `git ls-files`
(INDEX authority — a .gitignore entry never untracks what was committed
before it existed) instead of scanning the disk.

What THIS repo's CI writes inside the checkout (inventory @c50):
  - the py39-floor job redirects vermin stdout to `vermin.log` (secrets.yml
    'Floor claim machine-pinned' step).
  - the verify-release negative-controls job checks the verifier tool out to
    `.ethkey-tools/ethkey.py` in-tree (actions/checkout `path:`).
  Nothing else: every matrix script (findings-output-matrix,
    scan-root-matrix) writes fixtures under tempfile.mkdtemp/mkdtemp
    OUTSIDE the checkout, and negative-controls fixtures are COMMITTED
    files under proofs/, never generated.
The rails this repo must never lose:

  A. BLOCKLIST: no generated-file name may ever be tracked again.
  B. SCRATCH SWEEP: no tracked *.log / *.out at any depth (the step.log
     class generalized by extension, so a NEW log name is caught even when
     nobody added it to leg A).
  C. DOC DENOMINATOR: any tracked .md outside proofs/ must be named in
     DOC_ALLOW (README + SECURITY today). A new tracked .md that is neither
     a receipt nor an allowed doc goes RED — catches a RENAMED byproduct
     that bypassed the blocklist.

Exit codes: 0 clean, 1 a violation is printed, 2 bad usage / no git repo.
"""
import subprocess
import sys

# Files the CI harness WRITES inside this checkout. They must never be
# tracked (git ls-files) -- present-in-worktree is by construction,
# present-in-git is an accident.
BLOCKLIST = {
    "vermin.log",                # py39-floor job: vermin stdout (secrets.yml)
    ".ethkey-tools/ethkey.py",   # verify-release: verifier tool checkout
}

# Tracked .md files outside proofs/ must be enumerated here (docs).
DOC_ALLOW = {"README.md", "SECURITY.md"}


def tracked_files():
    r = subprocess.run(["git", "ls-files"], capture_output=True, text=True)
    if r.returncode != 0:
        print("FAIL: git ls-files failed: " + r.stderr.strip())
        sys.exit(2)
    return r.stdout.split()


def main():
    if len(sys.argv) > 1:
        print(__doc__.strip().splitlines()[-1])
        return 2
    fails = 0
    files = tracked_files()

    # A. generated-file blocklist
    hits = sorted(set(files) & BLOCKLIST)
    for h in hits:
        print(f"FAIL: generated CI byproduct is tracked: {h}")
        fails += 1
    if not hits:
        print(f"OK: 0/{len(BLOCKLIST)} generated byproducts tracked")

    # B. scratch-name sweep: any tracked *.log / *.out at any depth
    scratch = sorted(f for f in files if f.endswith((".log", ".out")))
    for s in scratch:
        print(f"FAIL: tracked scratch log: {s}")
        fails += 1
    if not scratch:
        print("OK: no tracked *.log / *.out anywhere")

    # C. tracked .md outside proofs/ must be an allowed doc
    stray = sorted(
        f
        for f in files
        if f.endswith(".md")
        and not f.startswith("proofs/")
        and f not in DOC_ALLOW
    )
    for s in stray:
        print(f"FAIL: tracked .md outside proofs/ not in DOC_ALLOW: {s}")
        fails += 1
    if not stray:
        print("OK: tracked .md set == proofs/ receipts + DOC_ALLOW docs")

    if fails:
        print(f"artifact-hygiene: {fails} violation(s)")
        return 1
    print("artifact-hygiene: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
